name: Notifications CICD

on: 
  push:
    branches: ["main"]

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - run: exit 1
    
      - name: Notify Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Build Completed!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
  build:
    runs: windows-latest
    steps:
      - run: echo "Build Completed"
